In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.5.0+cu121


# Introduction to Tenors

### creating Tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# getting tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]],[[1,2,3],[3,4,5],[5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random Tensors

Why random tensors?

Random Tensors are important because the way many neural networks leran is that they start with tensors full of random numbers and then adjust those random numbers to better represent those numbers

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# create a random tensor od size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3211, 0.8663, 0.1362, 0.4532],
        [0.4068, 0.0915, 0.0187, 0.4838],
        [0.3959, 0.8740, 0.9173, 0.9864]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[8.5348e-01, 9.9784e-01, 6.2029e-01],
         [8.0676e-01, 6.6562e-01, 3.5482e-01],
         [7.9696e-01, 9.7947e-01, 5.7821e-02],
         ...,
         [2.5803e-04, 4.1360e-01, 5.5262e-01],
         [3.1534e-01, 6.1025e-01, 1.2504e-01],
         [6.3475e-02, 2.5493e-01, 5.1752e-02]],

        [[1.4307e-01, 1.9519e-01, 4.2730e-02],
         [3.6811e-01, 8.2750e-01, 2.3640e-02],
         [3.6338e-02, 5.1039e-01, 8.7213e-02],
         ...,
         [7.4216e-01, 4.2629e-01, 1.8289e-01],
         [9.4540e-02, 1.8358e-01, 5.9949e-01],
         [8.7134e-01, 3.1645e-01, 9.7677e-01]],

        [[5.1496e-01, 8.8727e-01, 4.4680e-02],
         [7.4663e-02, 2.3921e-01, 6.9876e-01],
         [5.0375e-01, 8.7362e-01, 8.2027e-01],
         ...,
         [5.3599e-01, 6.1461e-01, 2.3237e-01],
         [4.7472e-01, 3.7151e-01, 1.0023e-01],
         [4.7199e-01, 9.0700e-01, 6.2245e-01]],

        ...,

        [[6.8975e-01, 4.5319e-01, 7.9849e-02],
         [6.0097e-01, 8.4888e-01, 5.8198e-01]

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
torch.rand(224,224,3)

tensor([[[0.8677, 0.5743, 0.4276],
         [0.3722, 0.4755, 0.9118],
         [0.5350, 0.4701, 0.0345],
         ...,
         [0.2952, 0.1974, 0.2240],
         [0.7173, 0.6628, 0.1722],
         [0.1518, 0.8964, 0.9583]],

        [[0.9594, 0.0545, 0.4161],
         [0.3019, 0.8243, 0.7764],
         [0.1593, 0.4974, 0.5555],
         ...,
         [0.7014, 0.8962, 0.0239],
         [0.5969, 0.0420, 0.7183],
         [0.9537, 0.7515, 0.7693]],

        [[0.5562, 0.0168, 0.0924],
         [0.2016, 0.7282, 0.3799],
         [0.8658, 0.8295, 0.7654],
         ...,
         [0.4034, 0.8171, 0.5727],
         [0.6910, 0.6506, 0.9525],
         [0.0053, 0.1829, 0.0861]],

        ...,

        [[0.0242, 0.4645, 0.4086],
         [0.2203, 0.6860, 0.2008],
         [0.1561, 0.3115, 0.6870],
         ...,
         [0.6284, 0.4388, 0.8577],
         [0.5801, 0.3758, 0.0537],
         [0.7773, 0.2387, 0.7337]],

        [[0.4704, 0.3277, 0.5659],
         [0.7574, 0.7050, 0.9253],
         [0.

## Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones\

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## create a range of tensors and tensors-like

In [ ]:
# use torch.range()

one_to_ten = torch.arange(start =1, end = 1000, step = 100)
one_to_ten

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [ ]:
# creating tensor like

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note.** Tensor datatypes is one of the 3 big errors that we'll run into with pytorch and Deep Learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# float32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor.device

device(type='cpu')

### Manipulating Tensors (Tensor Operations)

Tensor Operations Include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Divison
* Matrix Multiplication


In [ ]:
# create a tensor

tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# multiplication

tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# subtract

tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try pytorch in_built function

torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multipliaction

Two main ways of performing multiplication in neural networks and deep learning :

1. Element-wise multiplication
2. Matrix Multiplication

In [ ]:
# Element-Wise Multiplication

tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 1.63 ms, sys: 0 ns, total: 1.63 ms
Wall time: 1.45 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 408 µs, sys: 25 µs, total: 433 µs
Wall time: 360 µs


tensor(14)

### one of the most common errors in deep learning : shape errors

In [ ]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# to fix out tensor shape issues , we can manipulate the shape of one of our tensors using transpose

In [ ]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Tensor Aggregation

Min Max Mean Sum

In [ ]:
# create a tensor

x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# the torch.mean() requires float32 datatype

torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
%%time
torch.sum(x)

CPU times: user 484 µs, sys: 27 µs, total: 511 µs
Wall time: 385 µs


tensor(450)

In [ ]:
%%time
x.sum()

CPU times: user 1.05 ms, sys: 1e+03 ns, total: 1.05 ms
Wall time: 1.06 ms


tensor(450)

# finding the positional min and max

In [ ]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs

x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs

x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshaping , Stacking, Squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swappd) in a certain way

In [ ]:
import torch

In [ ]:
x = torch.arange(1.,10.)

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)

x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing the view

z= x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)

z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all the single dimensions from a target tensor

x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

In [ ]:
import torch

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

## Pytorch tensors V/s Numpy

- numpy -> torch = `torch.from_numpy(ndarray)`
- torch -> numpy = `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# changing the value of array

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

to reduce the randomness in neural networks and pyTorch there is a concept of a **Random Seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
# creating two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7884, 0.3161, 0.5716, 0.1836],
        [0.5276, 0.5585, 0.6096, 0.5129],
        [0.2880, 0.8213, 0.8253, 0.7237]])
tensor([[0.7229, 0.1034, 0.9087, 0.4732],
        [0.1117, 0.7171, 0.8774, 0.7406],
        [0.3189, 0.5555, 0.6497, 0.6387]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# making some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors on GPU

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
# device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

# Putting tensors and models on the GPU

In [ ]:
# create a tensor

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## moving tensors back to cpu

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')